### ISSUE TITLE
arguments for the client and server

### ISSUE THREAD

**Issue by maedjyuk-ghoti** [aephynsa/remy2015#1]
Do we want to use flags?
`./server -p <port> -h <hostname>`
or just require them to come in order without flags?
`./server <port> <hostname>`

**Comment by mgglenn** [comment]
Flags

Grace Glenn

**Comment by aephynsa** [comment]
I'm taking them just in order. Flags imply that they are optional; these are required for the program to function. Also, there's less confusion about what the flags should be, if you recall the -t, -p fiasco last time.
